version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: symbolize-api
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: symbolize-frontend
    ports:
      - "80:80"
    depends_on:
      - api
    env_file:
      - ./.env
